

import { Product, VendorPublicProfile, Review } from './types';

export const ABKHAZIA_CITIES = [
  'Сухум',
  'Гагра',
  'Гудаута',
  'Пицунда',
  'Новый Афон',
  'Очамчира',
  'Ткуарчал',
  'Гал',
  'Цандрипш',
  'Агудзера'
];

export const MOCK_VENDORS: VendorPublicProfile[] = [
  {
    id: 'v_bookworld',
    name: 'Книжный Мир',
    description: 'Лучшая литература со всего света. Классика, современная проза и редкие издания.',
    image: 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507842217121-9e9f1929c5f7?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    joinedDate: '2023-01-15',
    status: 'active',
    vendorId: 'u_bookworld_owner',
    revenue: 450000
  },
  {
    id: 'v_tech',
    name: 'TechnoPoint',
    description: 'Официальный дилер электроники. Гарантия качества на все гаджеты.',
    image: 'https://images.unsplash.com/photo-1531297461136-82lw9b44d940?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    joinedDate: '2023-03-10',
    status: 'active',
    vendorId: 'qoK5mTF2Lo',
    revenue: 1200000
  },
  {
    id: 'v_style',
    name: 'Fashion House',
    description: 'Стильная одежда для всей семьи. Новые коллекции каждый сезон.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    joinedDate: '2022-11-05',
    status: 'active',
    vendorId: 'u_style_owner',
    revenue: 800000
  },
  {
    id: 'v_local',
    name: 'Дары Абхазии',
    description: 'Натуральные продукты от местных фермеров. Мед, чай, специи.',
    image: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
    rating: 5.0,
    joinedDate: '2022-08-20',
    status: 'active',
    vendorId: 'u_local_owner',
    revenue: 300000
  }
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', productId: '1', userId: 'u10', userName: 'Елена С.', rating: 5, comment: 'Прекрасное издание! Бумага плотная, шрифт удобный. Доставили за один день.', date: '2024-03-10' },
  { id: 'r2', productId: '1', userId: 'u11', userName: 'Игорь В.', rating: 4, comment: 'Книга отличная, но уголок был немного помят при транспортировке.', date: '2024-03-12' },
  { id: 'r3', productId: '2', userId: 'u12', userName: 'Максим', rating: 5, comment: 'Телефон - пушка! Перешел с 11-го, разница колоссальная. Камера снимает как в кино.', date: '2024-03-15' },
  { id: 'r4', productId: '3', userId: 'u13', userName: 'Анна К.', rating: 5, comment: 'Самый вкусный мед, который я пробовала! Чувствуется натуральность.', date: '2024-03-18' }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    price: 850,
    oldPrice: 1200,
    category: 'Books',
    image: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 1240,
    description: 'Бессмертная классика русской литературы. История о дьяволе, посетившем Москву, и великой любви.',
    tags: ['fiction', 'classic', 'russian_lit'],
    isNew: false,
    inStock: true,
    vendorId: 'v_bookworld',
  },
  {
    id: '2',
    title: 'Apple iPhone 15 Pro',
    author: 'Apple',
    price: 115000,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
    rating: 5.0,
    reviewsCount: 42,
    description: 'Титановый корпус, процессор A17 Pro, кнопка Action Button. Самый мощный iPhone.',
    tags: ['smartphones', 'apple', 'iphone_15', 'phones'],
    isNew: true,
    inStock: true,
    vendorId: 'v_tech',
  },
  {
    id: '3',
    title: 'Абхазский мед (Каштан)',
    author: 'Местный Фермер',
    price: 1200,
    category: 'Food',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 89,
    description: 'Натуральный горный мед из Абхазии. Собран в экологически чистых районах.',
    tags: ['local', 'honey', 'organic', 'grocery'],
    inStock: true,
    vendorId: 'v_local',
  },
  {
    id: '4',
    title: 'Худи Oversize',
    author: 'Горизонт Brand',
    price: 3500,
    oldPrice: 4900,
    category: 'Men',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    reviewsCount: 215,
    description: 'Уютное худи из плотного хлопка. Идеально для прохладных вечеров.',
    tags: ['m_hoodies', 'm_clothes'],
    isNew: true,
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '5',
    title: 'Конструктор LEGO City',
    author: 'LEGO',
    price: 4500,
    oldPrice: 5200,
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 320,
    description: 'Полицейский участок с машинками и вертолетом. Отличный подарок для детей от 6 лет.',
    tags: ['constructors', 'lego'],
    inStock: true,
    vendorId: 'v_bookworld',
  },
  {
    id: '6',
    title: 'Футбольный мяч PRO',
    author: 'Adidas',
    price: 2900,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    reviewsCount: 55,
    description: 'Профессиональный мяч для тренировок и игр. Устойчив к износу.',
    tags: ['fitness', 'football'],
    isNew: true,
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '7',
    title: 'Набор уходовой косметики',
    author: 'Mixit',
    price: 1800,
    oldPrice: 2500,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 150,
    description: 'Комплексный уход за кожей лица: тоник, сыворотка и крем. Сияние и увлажнение.',
    tags: ['face', 'makeup'],
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '8',
    title: 'Автомобильный пылесос',
    author: 'Baseus',
    price: 3200,
    category: 'Auto',
    image: 'https://images.unsplash.com/photo-1552655909-64476059d48b?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    reviewsCount: 78,
    description: 'Компактный и мощный пылесос для уборки салона автомобиля. Работает от аккумулятора.',
    tags: ['car_electronics', 'cleaning'],
    inStock: true,
    vendorId: 'v_tech',
  },
  {
    id: '9',
    title: 'Кукла Барби Fashionistas',
    author: 'Mattel',
    price: 1500,
    category: 'Toys',
    image: 'https://images.unsplash.com/photo-1560935398-9419b48c1871?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    reviewsCount: 88,
    description: 'Стильная кукла в модном наряде. Развивает воображение и чувство стиля.',
    tags: ['dolls', 'barbie'],
    inStock: true,
    vendorId: 'v_bookworld',
  },
  {
    id: '10',
    title: 'Коврик для йоги',
    author: 'Demix',
    price: 990,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1593164842264-854604db0060?auto=format&fit=crop&w=600&q=80',
    rating: 4.4,
    reviewsCount: 45,
    description: 'Нескользящий коврик для занятий фитнесом и йогой. Толщина 6мм.',
    tags: ['fitness', 'yoga'],
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '11',
    title: 'Парфюмерная вода Floral',
    author: 'Gucci',
    price: 8500,
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1594035910387-fea4779426e9?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 22,
    description: 'Нежный цветочный аромат с нотами жасмина и розы. Стойкость до 24 часов.',
    tags: ['perfume', 'luxury'],
    isNew: true,
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '12',
    title: 'Видеорегистратор HD',
    author: 'Xiaomi',
    price: 4100,
    category: 'Auto',
    image: 'https://images.unsplash.com/photo-1516769992648-523173574c7e?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    reviewsCount: 110,
    description: 'Запись в высоком разрешении, ночной режим, датчик удара. Безопасность на дороге.',
    tags: ['car_electronics', 'dashcams'],
    inStock: true,
    vendorId: 'v_tech',
  },
  {
    id: '13',
    title: 'Диван угловой',
    author: 'IKEA',
    price: 45000,
    category: 'Furniture',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 20,
    description: 'Удобный угловой диван для гостиной. Тканевая обивка, раскладной механизм.',
    tags: ['living_room_furn', 'sofas'],
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '14',
    title: 'Зимняя куртка',
    author: 'Columbia',
    price: 12000,
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    reviewsCount: 45,
    description: 'Теплая куртка с мембраной. Защита от ветра и влаги.',
    tags: ['w_outerwear', 'w_clothes'],
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '15',
    title: 'Платье летнее',
    author: 'Zara',
    price: 3500,
    category: 'Women',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    reviewsCount: 112,
    description: 'Легкое платье из вискозы. Идеально для жаркой погоды.',
    tags: ['w_dresses', 'w_clothes'],
    inStock: true,
    vendorId: 'v_style',
  },
  {
    id: '16',
    title: 'Худильщик LG',
    author: 'LG',
    price: 55000,
    category: 'Appliances',
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    reviewsCount: 30,
    description: 'Двухкамерный холодильник с системой No Frost. Энергосбережение класса А++.',
    tags: ['large_appliances', 'fridges'],
    inStock: true,
    vendorId: 'v_tech',
  }
];
